FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache build-base gcc musl-dev linux-headers

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "profiling:app", "--host", "0.0.0.0", "--port", "8001"]